// <auto-generated />
using System;
using E_Comm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Comm.Migrations
{
    [DbContext(typeof(EntertainmentGuildContext))]
    [Migration("20250606081222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Comm.Models.BookGenre", b =>
                {
                    b.Property<int>("SubGenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subGenreID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubGenreID"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("SubGenreID");

                    b.ToTable("Book_genre", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<int?>("CVV")
                        .HasColumnType("int")
                        .HasColumnName("CVV");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CardNumber");

                    b.Property<string>("CardOwner")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CardOwner");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Expiry")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("Expiry");

                    b.Property<int?>("PatronId")
                        .HasColumnType("int")
                        .HasColumnName("PatronId");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int?>("PostCode")
                        .HasColumnType("int")
                        .HasColumnName("PostCode");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("State");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("StreetAddress");

                    b.Property<string>("Suburb")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Suburb");

                    b.HasKey("CustomerID");

                    b.HasIndex("PatronId");

                    b.ToTable("TO", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.GameGenre", b =>
                {
                    b.Property<int>("SubGenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subGenreID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubGenreID"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("SubGenreID");

                    b.ToTable("Game_genre", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("genreID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenreID");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.MovieGenre", b =>
                {
                    b.Property<int>("SubGenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subGenreID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubGenreID"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("SubGenreID");

                    b.ToTable("Movie_genre", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.Patron", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("HashPW")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("HashPW");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<string>("Salt")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Salt");

                    b.HasKey("UserID");

                    b.ToTable("Patrons", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenreID")
                        .HasColumnType("int")
                        .HasColumnName("Genre");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Published")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubGenre")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GenreID");

                    b.HasIndex("LastUpdatedBy");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.ProductsInOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProduktId")
                        .HasColumnType("int")
                        .HasColumnName("produktId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProduktId");

                    b.ToTable("ProductsInOrders", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sourceid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SourceId"));

                    b.Property<string>("ExternalLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenreID")
                        .HasColumnType("int")
                        .HasColumnName("Genre");

                    b.Property<string>("Source_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourceId");

                    b.HasIndex("GenreID");

                    b.ToTable("Source", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.Stocktake", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SourceId");

                    b.ToTable("Stocktake", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HashPW")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("isAdmin");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Salt")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserName");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("E_Comm.Models.Customer", b =>
                {
                    b.HasOne("E_Comm.Models.Patron", "Patron")
                        .WithMany("Customers")
                        .HasForeignKey("PatronId");

                    b.Navigation("Patron");
                });

            modelBuilder.Entity("E_Comm.Models.Order", b =>
                {
                    b.HasOne("E_Comm.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("E_Comm.Models.Product", b =>
                {
                    b.HasOne("E_Comm.Models.Genre", "Genre")
                        .WithMany("Products")
                        .HasForeignKey("GenreID");

                    b.HasOne("E_Comm.Models.User", "LastUpdatedByUser")
                        .WithMany()
                        .HasForeignKey("LastUpdatedBy");

                    b.Navigation("Genre");

                    b.Navigation("LastUpdatedByUser");
                });

            modelBuilder.Entity("E_Comm.Models.ProductsInOrder", b =>
                {
                    b.HasOne("E_Comm.Models.Order", "Order")
                        .WithMany("ProductsInOrders")
                        .HasForeignKey("OrderId");

                    b.HasOne("E_Comm.Models.Stocktake", "Stocktake")
                        .WithMany("ProductsInOrders")
                        .HasForeignKey("ProduktId");

                    b.Navigation("Order");

                    b.Navigation("Stocktake");
                });

            modelBuilder.Entity("E_Comm.Models.Source", b =>
                {
                    b.HasOne("E_Comm.Models.Genre", "Genre")
                        .WithMany("Sources")
                        .HasForeignKey("GenreID");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("E_Comm.Models.Stocktake", b =>
                {
                    b.HasOne("E_Comm.Models.Product", "Product")
                        .WithMany("Stocktakes")
                        .HasForeignKey("ProductId");

                    b.HasOne("E_Comm.Models.Source", "Source")
                        .WithMany("Stocktakes")
                        .HasForeignKey("SourceId");

                    b.Navigation("Product");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("E_Comm.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("E_Comm.Models.Genre", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("E_Comm.Models.Order", b =>
                {
                    b.Navigation("ProductsInOrders");
                });

            modelBuilder.Entity("E_Comm.Models.Patron", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("E_Comm.Models.Product", b =>
                {
                    b.Navigation("Stocktakes");
                });

            modelBuilder.Entity("E_Comm.Models.Source", b =>
                {
                    b.Navigation("Stocktakes");
                });

            modelBuilder.Entity("E_Comm.Models.Stocktake", b =>
                {
                    b.Navigation("ProductsInOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
